# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DaveoIdeoBox' do
  pod 'BubbleTransition', '~> 1.0.0'
end

target 'DaveoIdeoBoxTests' do

end

target 'DaveoIdeoBoxUITests' do

end
